version: '3.8'

services:
  web:
    build: .
    command: /app/run_wsgi.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
  db:
    image: postgres:13.1
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=pia
      - POSTGRES_PASSWORD=pia
      - POSTGRES_DB=pia
